### PR TITLE
001 view job roles

### PR DESCRIPTION
**Pull request by JennicaMistry**
Add the UI Skeleton with the GDS folder

### CODE REVIEW

**Review by KainosDanny — CHANGES_REQUESTED** [review]
remove doc folder :)

**Review by hellofadude — CHANGES_REQUESTED** [review]
Remove docs folder

**Review by Kahrym — CHANGES_REQUESTED** [review]
Doc folder removed

**Review by KainosDanny — APPROVED** [review]

**Review by hellofadude — APPROVED** [review]
Approved!

**Review by Kahrym — APPROVED** [review]

**Pull request merged**
